src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Groups("contact:read")
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @Groups("contact:read")
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @Groups("contact:read")
     * @ORM\Column(type="string", length=255)
     */
    private $mail;

    /**
     * @Groups("contact:read")
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/ContactType.php
<?php

namespace App\Form;
//namespace Aurel\ContactBundle\Form;

use App\Entity\Contact;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prenom', TextType::class,['attr' => ['placeholder' => 'prénom']])
            ->add('nom', TextType::class, ['attr'=>['placeholder'=> 'nom']])
            ->add('mail',EmailType::class, ['attr'=>['placeholder'=> 'email']])
            ->add('description', TextareaType::class, ['attr'=>['placeholder'=> 'description' ]])
            ->getForm();
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Contact::class,
        ]);
    }
}

templates/form/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
    <br>
    {% for label, messages in app.flashes %}
    {% for message in messages %}
        <div class="alert alert-{{ label }} mt-4 mb-4" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div><br>
    {% endfor %}
    {% endfor %}

    {% for contact in contacts %}
<section id="cover">
    <div id="cover-caption">
        <div id="container">
            <div class="col-sm-10 col-sm offset-1">
                <table class="table table-hover">
                    <tbody>
                        <tr class="table-active">
                            <th scope="primary"><h4>{{ contact.prenom }} {{ contact.nom }}</h4></th>
                            <td><h5>{{ contact.mail}}</h5></td>
                            <td>{{ contact.description }}</td>
                            <td>le {{ contact.createdAt|date("d/m/Y") }} à {{ contact.createdAt|date("H:i") }}</td>
                            <td>
                                <form method="post" action="{{ path('delete_contact', {'id': contact.id}) }}" style="display: inline-block" onsubmit="return confirm('Êtes vous vraiment sûr ?')">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contact.id) }}">
                                    <button class="btn btn-danger">Supprimer</button>
                                </form>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section><br>

    {% endfor %}

{% endblock %}

templates/form/email.html.twig
    <!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>

<div class="image">
    <img src="https://pngimage.net/wp-content/uploads/2018/06/orange-header-png.png" alt="imageHeader" >
</div>
<br>
<span class="preheader">{{ prenom }} {{ nom }} vous demande des informations </span>
<p><h2>Description</h2></p>
<p>{{ description }}</p>


<form action="mailto:{{ mail }}" method="GET">
    <input type="submit" value="Recontacter" />
</form>


<div class="image-footer">
    <img src="https://www.pngkit.com/png/full/253-2539875_orange-curve-line-png.png" alt="imageFooter">
</div>
</body>
</html>

templates/form/formulaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formulaire{% endblock %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}
<br>
    <section id="cover">
        <div id="cover-caption">
            <div id="container">
                <div class="col-sm-10 col-sm offset-1">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Formulaire de de demande</h4>
                            {{ form_start(form) }}
                            <div class="row align-items-end">
                                <div class="col">
                                    {{ form_row(form.prenom) }}
                                </div>
                                <div class="col">
                                    {{ form_row(form.nom) }}
                                </div>
                            </div>
                            {{ form_rest(form) }}
                                <button type="submit" class="btn btn-secondary">Envoyer</button>
                                {{ form_end(form) }}
                            </div>
                        </div>
                    </div>
                </div>
                <br>
            </div>
        </div>
</section>
{% endblock %}